In [1]:
import pandas as pd
csv_data = "dupl_removed_final3.csv"

In [2]:
music_df = pd.read_csv(csv_data)

In [3]:
music_df.head()

,artist_names,track_name,rank,weeks_on_chart,streams,week,danceability,energy,loudness,speechiness,acousticness,valence,tempo,duration,country
0,SyKo,#BrooklynBloodPop!,189,2.0,6046.0,2021-07-29,0.691,0.814,-3.788,0.117,0.0164,0.509,132.012,146.0,Bulgaria
1,SyKo,#BrooklynBloodPop!,79,1.0,7204.0,2021-05-06,0.691,0.814,-3.788,0.117,0.0164,0.509,132.012,146.0,Estonia
2,SyKo,#BrooklynBloodPop!,54,2.0,9060.0,2021-05-13,0.691,0.814,-3.788,0.117,0.0164,0.509,132.012,146.0,Estonia
3,SyKo,#BrooklynBloodPop!,71,3.0,8243.0,2021-05-20,0.691,0.814,-3.788,0.117,0.0164,0.509,132.012,146.0,Estonia
4,SyKo,#BrooklynBloodPop!,108,4.0,7515.0,2021-05-27,0.691,0.814,-3.788,0.117,0.0164,0.509,132.012,146.0,Estonia

In [4]:
countries_data = music_df.groupby(music_df['country'])['danceability', 'energy','loudness',
       'speechiness', 'acousticness','valence', 'tempo', 'duration'].mean()

C:\Users\ankit\AppData\Local\Temp\ipykernel_18932\2272196859.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  countries_data = music_df.groupby(music_df['country'])['danceability', 'energy','loudness',

In [5]:
countries_attrib_df = pd.DataFrame(countries_data).sort_values(['country'])
countries_attrib_df

,danceability,energy,loudness,speechiness,acousticness,valence,tempo,duration
country,,,,,,,,
Argentina,0.744013,0.675101,-5.216302,0.131787,0.229910,0.646563,120.360768,206.661807
Australia,0.647711,0.633686,-6.481121,0.095834,0.254743,0.504944,120.494618,210.157895
Austria,0.690939,0.671089,-6.318950,0.111944,0.213600,0.532730,123.415775,187.416711
Belarus,0.685134,0.656724,-7.133241,0.125515,0.213192,0.455123,124.346252,171.488864
Belgium,0.696079,0.677366,-6.198538,0.108677,0.218400,0.549937,122.500907,197.808202
...,...,...,...,...,...,...,...,...
United Kingdom,0.653637,0.657538,-6.436920,0.111578,0.235264,0.526514,122.010783,205.712368
United States,0.664687,0.615787,-6.715155,0.118298,0.237849,0.471877,122.537318,202.663399
Uruguay,0.715186,0.675496,-5.322464,0.105967,0.242609,0.636782,122.401861,202.354694
Venezuela,0.724298,0.688508,-5.317021,0.110129,0.250157,0.587370,121.701712,208.170294
Vietnam,0.643859,0.533608,-7.457486,0.066739,0.454610,0.446536,119.133977,221.938514

In [6]:
csv_data2 = "artist_genres.csv"
genre_df = pd.read_csv(csv_data2)
genre_df

                                 artist_names            artist_genre
0                        Bad Bunny, Tony Dize           latin hip hop
1        Blessd, Justin Quiles, Lenny Tavárez               reggaeton
2        Blessd, Justin Quiles, Lenny Tavárez               reggaeton
3        Blessd, Justin Quiles, Lenny Tavárez          reggaeton flow
4                Eladio Carrion, Nicki Nicole             trap triste
...                                       ...                     ...
1099768                                   BTS         k-pop boy group
1099769                                   BTS         k-pop boy group
1099770                                 GAYLE  modern alternative pop
1099771                                Da LAB                   v-pop
1099772                                   Vũ.                   v-pop

[1099773 rows x 2 columns]

In [7]:
genre_df = genre_df.loc[genre_df['artist_genre'] != '0']

In [8]:
most_pop_genres_df = pd.DataFrame(genre_df.groupby(genre_df['artist_genre']).count())

most_pop_genres_df = most_pop_genres_df.sort_values(['artist_names'], ascending=False)
top_fifty_genres_df = most_pop_genres_df.head(50)

top_fifty_genres_df

                           artist_names
artist_genre
pop                              107610
trap latino                       40392
latin                             34474
reggaeton                         33662
dance pop                         31377
rap                               19871
uk pop                            17790
k-pop                             15272
canadian pop                      14007
hip hop                            9630
reggaeton colombiano               8903
pop rap                            8743
german hip hop                     8521
trap                               8477
latin pop                          8472
pop dance                          7472
melodic rap                        7364
tropical house                     6754
chicago rap                        6380
k-pop boy group                    6323
canadian contemporary r&b          6282
latin hip hop                      6246
j-pop                              6231
australian hip hop                 6224
israeli pop                        6030
trap argentino                     5795
edm                                5748
reggaeton flow                     5743
r&b                                5698
puerto rican pop                   5697
cantopop                           5617
modern rock                        5536
danish pop                         5384
mandopop                           5326
greek trap                         5243
indonesian pop                     5126
arrocha                            5052
brooklyn drill                     4974
electropop                         4889
italian pop                        4853
russian hip hop                    4566
rock                               4513
thai pop                           4431
slap house                         4414
dutch pop                          4376
post-teen pop                      4375
polish hip hop                     4142
egyptian hip hop                   4046
lgbtq+ hip hop                     4038
colombian pop                      4001

In [9]:
top_fifty_genres_df.columns

Index(['artist_names'], dtype='object')

In [10]:
music_df.columns

Index(['artist_names', 'track_name', 'rank', 'weeks_on_chart', 'streams',
       'week', 'danceability', 'energy', 'loudness', 'speechiness',
       'acousticness', 'valence', 'tempo', 'duration', 'country'],
      dtype='object')

In [11]:
aver_rank_streams = music_df.groupby(['artist_names','track_name'])['rank','streams'].mean().round(0)
aver_rank_streams_df = pd.DataFrame(aver_rank_streams)
#music_df.groupby(music_df['country'])['danceability', 'energy','loudness',
       #'speechiness', 'acousticness','valence', 'tempo', 'duration'].mean()
aver_rank_streams_df

C:\Users\ankit\AppData\Local\Temp\ipykernel_18932\3659512825.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  aver_rank_streams = music_df.groupby(['artist_names','track_name'])['rank','streams'].mean().round(0)

                                                                               rank  \
artist_names                      track_name
#TocoParaVos, El Reja, Marka Akme Se Picó                                      94.0
$NOT                              GOSHA                                       155.0
$NOT, A$AP Rocky                  Doja                                        108.0
$NOT, Lil Skies, Internet Money   Whipski (feat. Lil Skies & Internet Money)  138.0
$OHO BANI                         VIRAL                                       138.0
...                                                                             ...
魚丁糸                               Leave Me Alone (魚in summer)                 198.0
                                  Sorry青春                                     119.0
                                  終點起點                                         81.0
麗英@小薯茄                            東京一轉                                        146.0
黄霄雲                               STARS AND SEA                               110.0

                                                                               streams
artist_names                      track_name
#TocoParaVos, El Reja, Marka Akme Se Picó                                     137573.0
$NOT                              GOSHA                                         5724.0
$NOT, A$AP Rocky                  Doja                                        242309.0
$NOT, Lil Skies, Internet Money   Whipski (feat. Lil Skies & Internet Money)  440500.0
$OHO BANI                         VIRAL                                       398532.0
...                                                                                ...
魚丁糸                               Leave Me Alone (魚in summer)                  44632.0
                                  Sorry青春                                      56957.0
                                  終點起點                                         77530.0
麗英@小薯茄                            東京一轉                                         28442.0
黄霄雲                               STARS AND SEA                                70289.0

[27905 rows x 2 columns]

In [12]:
aver_rank_streams_df = aver_rank_streams_df.reset_index()
aver_rank_streams_df = aver_rank_streams_df[['artist_names','track_name','rank','streams']]
aver_rank_streams_df

,artist_names,track_name,rank,streams
0,"#TocoParaVos, El Reja, Marka Akme",Se Picó,94.0,137573.0
1,$NOT,GOSHA,155.0,5724.0
2,"$NOT, A$AP Rocky",Doja,108.0,242309.0
3,"$NOT, Lil Skies, Internet Money",Whipski (feat. Lil Skies & Internet Money),138.0,440500.0
4,$OHO BANI,VIRAL,138.0,398532.0
...,...,...,...,...
27900,魚丁糸,Leave Me Alone (魚in summer),198.0,44632.0
27901,魚丁糸,Sorry青春,119.0,56957.0
27902,魚丁糸,終點起點,81.0,77530.0
27903,麗英@小薯茄,東京一轉,146.0,28442.0
27904,黄霄雲,STARS AND SEA,110.0,70289.0

In [13]:
max_weeks_on_chart = music_df.groupby(['artist_names','track_name'])['weeks_on_chart'].max()
max_weeks_on_chart_df = pd.DataFrame(max_weeks_on_chart).sort_values(['weeks_on_chart'], ascending=False)
max_weeks_on_chart_df = max_weeks_on_chart_df.reset_index()

In [14]:
max_weeks_on_chart_df.columns

Index(['artist_names', 'track_name', 'weeks_on_chart'], dtype='object')

In [15]:
coolness_df = pd.merge(max_weeks_on_chart_df,aver_rank_streams_df,how='left',left_on=['artist_names','track_name'],right_on=['artist_names','track_name'])

In [16]:
coolness_df['WOC_ratio'] = coolness_df['weeks_on_chart'].div(290).round(3)
coolness_df.head(40)

,artist_names,track_name,weeks_on_chart,rank,streams,WOC_ratio
0,Ed Sheeran,Photograph,290.0,147.0,130715.0,1.000
1,Hebe Tien,小幸運,290.0,108.0,54015.0,1.000
2,"Anuel AA, Daddy Yankee, Zion & Lennox, Farruko...",Sola (Remix),290.0,137.0,45522.0,1.000
3,James Arthur,Say You Won't Let Go,290.0,124.0,163759.0,1.000
4,South Border,Rainbow,290.0,78.0,386851.0,1.000
5,Eric Chou,How Have You Been? - Ending Theme Song of TVBS...,290.0,100.0,58119.0,1.000
6,Dear Jane,You and Me,290.0,118.0,32287.0,1.000
7,The Killers,Mr. Brightside,290.0,97.0,591710.0,1.000
8,Danny Ocean,Me Rehúso,290.0,97.0,177402.0,1.000
9,Jason Chan,你瞞我瞞,290.0,111.0,33423.0,1.000
10,Alejandro Fernández,Me Dediqué a Perderte,290.0,159.0,146012.0,1.000
11,Jay Chou,告白氣球,290.0,118.0,48360.0,1.000
12,León Larregui,Brillas,290.0,100.0,979170.0,1.000
13,Kay Tse,囍帖街,290.0,94.0,36024.0,1.000
14,Bacilos,Caraluna,290.0,149.0,51525.0,1.000
15,Terence Siufay,Shi Guang Ji,290.0,143.0,26863.0,1.000
16,Luis Miguel,Ahora Te Puedes Marchar,290.0,141.0,364695.0,1.000
17,Payung Teduh,Untuk Perempuan Yang Sedang Di Pelukan,290.0,112.0,350486.0,1.000
18,"The Chainsmokers, Halsey",Closer,289.0,150.0,116525.0,0.997
19,G.E.M.,光年之外 (電影 《Passengers》 中國區主題曲),289.0,137.0,54516.0,0.997
20,"Bonez MC, RAF Camora, Maxwell",Ohne mein Team,288.0,108.0,66826.0,0.993
21,Vance Joy,Riptide,286.0,139.0,132946.0,0.986
22,Punnany Massif,Élvezd,285.0,108.0,30988.0,0.983
23,Jay Chou,晴天,285.0,145.0,45364.0,0.983
24,Oasis,Wonderwall - Remastered,285.0,135.0,238526.0,0.983
25,Imagine Dragons,Believer,284.0,157.0,82716.0,0.979
26,Christina Perri,A Thousand Years,284.0,169.0,75528.0,0.979
27,"Yura Yunita, Glenn Fredly",Cinta Dan Rahasia,283.0,146.0,298473.0,0.976
28,mor ve ötesi,Bir Derdim Var,283.0,101.0,354796.0,0.976
29,"The Chainsmokers, Coldplay",Something Just Like This,282.0,149.0,41056.0,0.972
30,Eagles,Hotel California - 2013 Remaster,282.0,137.0,131745.0,0.972
31,Bubbi Morthens,Rómeó og Júlía,281.0,61.0,10140.0,0.969
32,Ed Sheeran,Perfect,280.0,142.0,89770.0,0.966
33,Manuel Medrano,Bajo El Agua,280.0,165.0,59731.0,0.966
34,Up Dharma Down,Tadhana,278.0,139.0,251876.0,0.959
35,Eraserheads,Ang Huling El Bimbo,278.0,150.0,246963.0,0.959
36,Ed Sheeran,Shape of You,277.0,157.0,97713.0,0.955
37,Hjálmar,Leiðin okkar allra,277.0,115.0,6520.0,0.955
38,J. Cole,No Role Modelz,277.0,114.0,305076.0,0.955
39,Hins Cheung,春秋,276.0,66.0,47294.0,0.952

In [17]:
coolness_df['rank'].max()

200.0

In [18]:
rank_pts = []
for row in coolness_df['rank']:
    rank_pts.append((100 - (row * .5))/100)

In [19]:
coolness_df['rank_pts'] = rank_pts

In [20]:
coolness_df.sort_values(['rank_pts'],ascending=False)

,artist_names,track_name,weeks_on_chart,rank,streams,WOC_ratio,rank_pts
10104,Mata,Kiss cam (podryw roku),15.0,1.0,2026317.0,0.052,0.995
20985,Formalite,Mahvettim,2.0,1.0,23120.0,0.007,0.995
11965,"Abdul Hannan, Rovalio",Bikhra,10.0,1.0,203875.0,0.034,0.995
16122,"Light, Trannos",24hrs,5.0,1.0,503930.0,0.017,0.995
11575,Keung To,作品的說話,11.0,1.0,285090.0,0.038,0.995
...,...,...,...,...,...,...,...
21685,Oxxxymiron,Улет,2.0,200.0,28298.0,0.007,0.000
24705,"Falz, Kamo Mphela, Mpura, Niniola, Sayfar",Squander (feat. Niniola & Sayfar) - Remix,1.0,200.0,18243.0,0.003,0.000
21746,Bet Bet,Man Vienalga Viss,2.0,200.0,6123.0,0.007,0.000
24605,"Ege Zulu, Jore",Peter Pan,1.0,200.0,37287.0,0.003,0.000
14143,"Hard GZ, Nikone, Dualy",Lo Real,7.0,200.0,242176.0,0.024,0.000

In [21]:
coolness_df['streams_ratio'] = coolness_df['streams'].div(4026918).round(3)
coolness_df.sort_values(['streams_ratio'],ascending=False)

,artist_names,track_name,weeks_on_chart,rank,streams,WOC_ratio,rank_pts,streams_ratio
12446,João Gomes,Dengo,10.0,20.0,4025622.0,0.034,0.900,1.000
8861,Tulus,Hati-Hati di Jalan,19.0,9.0,4026918.0,0.066,0.955,1.000
13722,Keisya Levronka,Tak Ingin Usai,8.0,3.0,3624225.0,0.028,0.985,0.900
4292,Henrique & Juliano,A Maior Saudade - Ao Vivo,45.0,19.0,3549891.0,0.155,0.905,0.882
12481,Jorge & Mateus,Todo Seu - Ao Vivo,10.0,18.0,3496942.0,0.034,0.910,0.868
...,...,...,...,...,...,...,...,...
22425,"margiiela, Leis",üks öö (feat. Leis),1.0,192.0,4584.0,0.003,0.040,0.001
4053,Bubbi Morthens,Regnbogans stræti,48.0,150.0,5626.0,0.166,0.250,0.001
22405,"marp$, Raul",reede,1.0,147.0,5387.0,0.003,0.265,0.001
22381,yung fin,Paparazzi,1.0,155.0,3938.0,0.003,0.225,0.001
7202,Jón Jónsson,Ljúft að vera til,25.0,180.0,5726.0,0.086,0.100,0.001

In [22]:
coolness_df['Popularity_Score'] = (coolness_df['WOC_ratio'] + coolness_df['rank_pts'] + coolness_df['streams_ratio'])/3

In [23]:
coolness_df = coolness_df.sort_values(['Popularity_Score'],ascending=False)
coolness_df.head(5)

,artist_names,track_name,weeks_on_chart,rank,streams,WOC_ratio,rank_pts,streams_ratio,Popularity_Score
8861,Tulus,Hati-Hati di Jalan,19.0,9.0,4026918.0,0.066,0.955,1.000,0.673667
4292,Henrique & Juliano,A Maior Saudade - Ao Vivo,45.0,19.0,3549891.0,0.155,0.905,0.882,0.647333
12446,João Gomes,Dengo,10.0,20.0,4025622.0,0.034,0.900,1.000,0.644667
13722,Keisya Levronka,Tak Ingin Usai,8.0,3.0,3624225.0,0.028,0.985,0.900,0.637667
12481,Jorge & Mateus,Todo Seu - Ao Vivo,10.0,18.0,3496942.0,0.034,0.910,0.868,0.604000

In [24]:
usa_df = music_df.loc[music_df['country'] == 'United States']
usa_df.head(5)

,artist_names,track_name,rank,weeks_on_chart,streams,week,danceability,energy,loudness,speechiness,acousticness,valence,tempo,duration,country
184,Cody Johnson,'Til You Can't,154,1.0,1556168.0,2021-10-14,0.501,0.815,-4.865,0.0436,0.0513,0.46,160.087,224.0,United States
185,Cody Johnson,'Til You Can't,158,2.0,1689695.0,2022-03-03,0.501,0.815,-4.865,0.0436,0.0513,0.46,160.087,224.0,United States
186,Cody Johnson,'Til You Can't,151,3.0,1727287.0,2022-03-10,0.501,0.815,-4.865,0.0436,0.0513,0.46,160.087,224.0,United States
187,Cody Johnson,'Til You Can't,183,4.0,1576313.0,2022-03-17,0.501,0.815,-4.865,0.0436,0.0513,0.46,160.087,224.0,United States
188,Cody Johnson,'Til You Can't,135,5.0,1793033.0,2022-03-24,0.501,0.815,-4.865,0.0436,0.0513,0.46,160.087,224.0,United States

In [25]:
usa_df = usa_df.drop_duplicates(subset=['artist_names','track_name'],keep='first')
usa_df = usa_df[['artist_names','track_name','country']]
usa_df

,artist_names,track_name,country
184,Cody Johnson,'Til You Can't,United States
778,"Eminem, Nate Dogg",'Till I Collapse,United States
799,Kay Starr,(Everybody's Waitin' For) The Man With The Bag...,United States
824,Perry Como,(There's No Place Like) Home for the Holidays ...,United States
1185,$uicideboy$,"...And to Those I Love, Thanks for Sticking Ar...",United States
...,...,...,...
687675,Taylor Swift,willow,United States
687756,"Tate McRae, Khalid",working,United States
687758,Ariana Grande,worst behavior,United States
687794,"Gunna, Chlöe",you & me,United States
689072,Tate McRae,you broke me first,United States

In [26]:
usa_coolness_df = pd.merge(coolness_df,usa_df,how='inner',left_on=['artist_names','track_name'],right_on=['artist_names','track_name'])
usa_coolness_df = usa_coolness_df.sort_values(['Popularity_Score'],ascending=False)
usa_coolness_df.head(20)

,artist_names,track_name,weeks_on_chart,rank,streams,WOC_ratio,rank_pts,streams_ratio,Popularity_Score,country
0,The Killers,Mr. Brightside,290.0,97.0,591710.0,1.000,0.515,0.147,0.554000,United States
1,Kid Cudi,love.,1.0,29.0,3233804.0,0.003,0.855,0.803,0.553667,United States
2,Fleetwood Mac,Dreams - 2004 Remaster,260.0,96.0,481432.0,0.897,0.520,0.120,0.512333,United States
3,J. Cole,No Role Modelz,277.0,114.0,305076.0,0.955,0.430,0.076,0.487000,United States
4,Morgan Wallen,You Proof,9.0,40.0,2442435.0,0.031,0.800,0.607,0.479333,United States
5,James Arthur,Say You Won't Let Go,290.0,124.0,163759.0,1.000,0.380,0.041,0.473667,United States
6,"Bad Bunny, Chencho Corleone",Me Porto Bonito,10.0,36.0,2216389.0,0.034,0.820,0.550,0.468000,United States
7,"Bad Bunny, Rauw Alejandro",Party,10.0,18.0,1839393.0,0.034,0.910,0.457,0.467000,United States
8,Lil Uzi Vert,XO Tour Llif3,266.0,158.0,946951.0,0.917,0.210,0.235,0.454000,United States
9,"Bad Bunny, Jhay Cortez",Tarot,10.0,18.0,1574209.0,0.034,0.910,0.391,0.445000,United States
10,Travis Scott,goosebumps,274.0,133.0,208581.0,0.945,0.335,0.052,0.444000,United States
11,Vance Joy,Riptide,286.0,139.0,132946.0,0.986,0.305,0.033,0.441333,United States
12,Eagles,Hotel California - 2013 Remaster,282.0,137.0,131745.0,0.972,0.315,0.033,0.440000,United States
13,Bad Bunny,Tití Me Preguntó,10.0,19.0,1525165.0,0.034,0.905,0.379,0.439333,United States
14,"Bad Bunny, Bomba Estéreo",Ojitos Lindos,10.0,34.0,1805233.0,0.034,0.830,0.448,0.437333,United States
15,"Trippie Redd, Ski Mask The Slump God",Demon Time (feat. Ski Mask The Slump God),1.0,63.0,2503491.0,0.003,0.685,0.622,0.436667,United States
16,Trippie Redd,Super Cell,1.0,65.0,2485063.0,0.003,0.675,0.617,0.431667,United States
17,"Bobby ""Boris"" Pickett, The Crypt-Kickers",Monster Mash,5.0,31.0,1740585.0,0.017,0.845,0.432,0.431333,United States
18,"J Balvin, Bad Bunny",LA CANCIÓN,159.0,71.0,396512.0,0.548,0.645,0.098,0.430333,United States
19,Joji,SLOW DANCING IN THE DARK,198.0,133.0,1057741.0,0.683,0.335,0.263,0.427000,United States

In [27]:
#import all dependencies for Sqlalchemy
from sqlalchemy import create_engine
import sqlite3

# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, Float, Boolean

In [28]:
music_conn = sqlite3.connect('music_db.sqlite')
print(music_conn)
music_df.to_sql('music', music_conn, if_exists='replace', index=False)

music_df = pd.read_sql_query('SELECT * FROM music', music_conn)
for music in music_df:
       print(music)

<sqlite3.Connection object at 0x000001A0622A05D0>
artist_names
track_name
rank
weeks_on_chart
streams
week
danceability
energy
loudness
speechiness
acousticness
valence
tempo
duration
country

In [29]:
coolness_conn = sqlite3.connect('coolness_db.sqlite')
print(coolness_conn)
coolness_df.to_sql('cool_music', coolness_conn, if_exists='replace', index=False)
music_conn.close
music_df = pd.read_sql_query('SELECT * FROM cool_music', coolness_conn)
for cool_music in coolness_df:
       print(cool_music)
coolness_conn.close

<sqlite3.Connection object at 0x000001A0207524E0>
artist_names
track_name
weeks_on_chart
rank
streams
WOC_ratio
rank_pts
streams_ratio
Popularity_Score

In [30]:
usa_cool_conn = sqlite3.connect('usa_cool_conn.sqlite')
print(usa_cool_conn)
usa_coolness_df.to_sql('usa_cool_music', usa_cool_conn, if_exists='replace', index=False)

usa_coolness_df = pd.read_sql_query('SELECT * FROM usa_cool_music', usa_cool_conn)
for cool_music in usa_coolness_df:
       print(cool_music)

<sqlite3.Connection object at 0x000001A0207523F0>
artist_names
track_name
weeks_on_chart
rank
streams
WOC_ratio
rank_pts
streams_ratio
Popularity_Score
country

In [1]:
#import all dependencies for Sqlalchemy
from sqlalchemy import create_engine
import sqlite3

# Import modules to declare columns and column data types
from sqlalchemy import Column, Integer, String, DECIMAL, DateTime



# Import and establish Base for which classes will be constructed 
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()

engine = create_engine('sqlite://', echo=False)

In [ ]:
class chart_rank(Base):
    __tablename__ = "chart_rank_db"
    song_id = Column(Integer, primary_key=True)
    rank = Column(Integer)
    country = Column(String, primary_key=True)
    weeks_on_chart = Column(Integer)
    week = Column(DateTime, primary_key=True)
    artist_id = Column(Integer, foreign_key = True)

In [6]:
# Create Database Connection
engine = create_engine('sqlite:///chart_rank_db.sqlite')
Base.metadata.create_all(engine)

In [ ]:
class song(Base):
    __tablename__ = "song_db"
    song_id = Column(Integer, primary_key=True)
    track_name = Column(String)
    streams = Column(Integer)
    artist_id = Column(Integer, foreign_key = True)

In [ ]:
class song_attributes(Base):
    __tablename__ = "attributes_db"
    song_id = Column(Integer, foreign_key=True)
    danceability = Column(DECIMAL)
    energy = Column(DECIMAL)
    loudness = Column(DECIMAL)
    speechiness = Column(DECIMAL)
    acousticness = Column(DECIMAL)
    valence = Column(DECIMAL)
    tempo =  Column(DECIMAL)
    duration = Column(DECIMAL)