In [2]:
import pandas as pd
csv_data = "final.csv"

In [3]:

music_df = pd.read_csv(csv_data)

C:\Users\cmbut\AppData\Local\Temp\ipykernel_237592\2569950116.py:1: DtypeWarning: Columns (2,4,9,12,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,31,35) have mixed types. Specify dtype option on import or set low_memory=False.
  music_df = pd.read_csv(csv_data)

In [4]:
music_df.head()

,Unnamed: 0,uri,rank,artist_names,artists_num,artist_individual,artist_id,artist_genre,artist_img,collab,...,acousticness,instrumentalness,liveness,valence,tempo,duration,country,region,language,pivot
0,0,spotify:track:2gpQi3hbcUAcEG8m2dlgfB,1,Paulo Londra,1.0,Paulo Londra,spotify:artist:3vQ0GE3mI0dAaxIMYe5g7z,argentine hip hop,https://i.scdn.co/image/ab6761610000e5ebf796a9...,0,...,0.0495,0.0,0.0658,0.557,173.935,178203.0,Argentina,South America,Spanish,0
1,1,spotify:track:2x8oBuYaObjqHqgGuIUZ0b,2,WOS,1.0,WOS,spotify:artist:5YCc6xS5Gpj3EkaYGdjyNK,argentine indie,https://i.scdn.co/image/ab6761610000e5eb75e151...,0,...,0.724,0.0,0.134,0.262,81.956,183547.0,Argentina,South America,Spanish,0
2,2,spotify:track:2SJZdZ5DLtlRosJ2xHJJJa,3,Paulo Londra,1.0,Paulo Londra,spotify:artist:3vQ0GE3mI0dAaxIMYe5g7z,argentine hip hop,https://i.scdn.co/image/ab6761610000e5ebf796a9...,0,...,0.241,0.0,0.0929,0.216,137.915,204003.0,Argentina,South America,Spanish,0
3,3,spotify:track:1O2pcBJGej0pmH2Y9XZMs6,5,Cris Mj,1.0,Cris Mj,spotify:artist:1Yj5Xey7kTwvZla8sqdsdE,urbano chileno,https://i.scdn.co/image/ab6761610000e5eb8f4ebc...,0,...,0.0924,0.000046,0.0534,0.832,96.018,153750.0,Argentina,South America,Spanish,0
4,4,spotify:track:1TpZKxGnHp37ohJRszTSiq,6,Emilia,1.0,Emilia,spotify:artist:0AqlFI0tz2DsEoJlKSIiT9,pop argentino,https://i.scdn.co/image/ab6761610000e5ebaf96d1...,0,...,0.0811,0.000063,0.101,0.501,95.066,133895.0,Argentina,South America,Spanish,0

In [5]:
music_df.columns

Index(['Unnamed: 0', 'uri', 'rank', 'artist_names', 'artists_num',
       'artist_individual', 'artist_id', 'artist_genre', 'artist_img',
       'collab', 'track_name', 'release_date', 'album_num_tracks',
       'album_cover', 'source', 'peak_rank', 'previous_rank', 'weeks_on_chart',
       'streams', 'week', 'danceability', 'energy', 'key', 'mode', 'loudness',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration', 'country', 'region', 'language',
       'pivot'],
      dtype='object')

In [87]:
music_reduced = music_df[['artist_names', 'track_name','rank', 'artists_num', 'artist_genre', 'release_date','weeks_on_chart',
       'streams', 'week', 'danceability', 'energy', 'key', 'loudness',
       'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration', 'country']]

In [88]:
music_reduced.head()

,artist_names,track_name,rank,artists_num,artist_genre,release_date,weeks_on_chart,streams,week,danceability,...,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,country
0,Paulo Londra,Plan A,1,1.0,argentine hip hop,2022-03-23,4,3003411,2022-04-14,0.583,...,0.0,-4.875,0.0444,0.0495,0.0,0.0658,0.557,173.935,178203.0,Argentina
1,WOS,ARRANCARMELO,2,1.0,argentine indie,2022-04-06,2,2512175,2022-04-14,0.654,...,5.0,-7.358,0.0738,0.724,0.0,0.134,0.262,81.956,183547.0,Argentina
2,Paulo Londra,Chance,3,1.0,argentine hip hop,2022-04-06,2,2408983,2022-04-14,0.721,...,1.0,-9.483,0.0646,0.241,0.0,0.0929,0.216,137.915,204003.0,Argentina
3,Cris Mj,Una Noche en Medellín,5,1.0,urbano chileno,2022-01-21,8,2080139,2022-04-14,0.87,...,10.0,-5.253,0.077,0.0924,0.000046,0.0534,0.832,96.018,153750.0,Argentina
4,Emilia,cuatro veinte,6,1.0,pop argentino,2022-03-24,3,1923270,2022-04-14,0.761,...,7.0,-3.817,0.0505,0.0811,0.000063,0.101,0.501,95.066,133895.0,Argentina

In [89]:
music_reduced.dtypes

artist_names        object
track_name          object
rank                object
artists_num         object
artist_genre        object
release_date        object
weeks_on_chart      object
streams             object
week                object
danceability        object
energy              object
key                 object
loudness            object
speechiness         object
acousticness        object
instrumentalness    object
liveness            object
valence             object
tempo               object
duration            object
country             object
dtype: object

In [90]:
#music_removed = music_reduced[~music_reduced.rank.str.contains("rank")]
music_removed = music_reduced[music_reduced['rank'].str.contains("rank") == False]

In [91]:
music_removed['rank'].str.strip()
music_removed['rank'].unique()

#points = df.points.unique()

array(['78', '79', '82', '86', '91', '92', '94', '96', '98', '100', '101',
       '102', '104', '105', '108', '109', '110', '111', '113', '114',
       '116', '118', '119', '120', '122', '126', '127', '128', '129',
       '131', '135', '137', '143', '144', '148', '152', '154', '157',
       '158', '159', '160', '161', '162', '163', '165', '166', '168',
       '169', '170', '171', '172', '180', '182', '183', '185', '191',
       '192', '194', '195', '198', '199', '200', '1', '2', '3', '4', '5',
       '6', '7', '8', '10', '11', '12', '14', '15', '16', '17', '19',
       '20', '21', '22', '23', '24', '25', '27', '29', '32', '33', '34',
       '36', '38', '39', '41', '42', '44', '45', '47', '48', '49', '50',
       '52', '53', '54', '55', '60', '62', '63', '64', '65', '66', '67',
       '68', '69', '71', '74', '77', '80', '81', '83', '85', '87', '89',
       '93', '99', '103', '106', '107', '123', '125', '133', '134', '139',
       '142', '149', '150', '153', '164', '167', '181', '184', '187',
       '188', '193', '196', '13', '18', '26', '28', '30', '31', '35',
       '40', '43', '46', '57', '59', '70', '73', '75', '76', '84', '90',
       '95', '97', '115', '121', '130', '141', '174', '175', '176', '177',
       '178', '189', '190', '9', '56', '58', '61', '88', '112', '117',
       '124', '132', '136', '138', '146', '156', '186', '145', '147',
       '155', '179', '197', '37', '51', '72', '140', '151', '173'],
      dtype=object)

In [94]:

# creating a dictionary 
# with column name and data type
#data_types_dict = {'artist_names': str, 'track_name': str, 'rank': int,'artists_num': float, 'artist_genre': str, 'peak_rank': int, 'previous_rank': int, 'weeks_on_chart': int,
       #'streams': int, 'danceability': float, 'energy': float, 'key': int, 'mode': int, 'loudness': float,
       #'speechiness': float, 'acousticness': float, 'instrumentalness': float, 'liveness': float,
       #'valence': float, 'tempo': float, 'duration': int, 'country': str, 'region': str}
data_types_dict = {'artist_names': str, 'track_name': str, 'rank': int,'artists_num': float, 'artist_genre': str,'weeks_on_chart': float,
       'streams': float, 'danceability': float, 'energy': float, 'key': float,'loudness': float,
       'speechiness': float, 'acousticness': float, 'instrumentalness': float, 'liveness': float,
       'valence': float, 'tempo': float, 'duration': float, 'country': str}
  
# we will change the data type 
# of id column to str by giving
# the dict to the astype method
music_removed = music_removed.astype(data_types_dict)
  
# checking the data types
# using df.dtypes method
music_removed.dtypes

artist_names         object
track_name           object
rank                  int32
artists_num         float64
artist_genre         object
release_date         object
weeks_on_chart      float64
streams             float64
week                 object
danceability        float64
energy              float64
key                 float64
loudness            float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
duration            float64
country              object
dtype: object

In [95]:
music_removed.head()

,artist_names,track_name,rank,artists_num,artist_genre,release_date,weeks_on_chart,streams,week,danceability,...,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,country
16384,"Bad Bunny, Tony Dize",La Corriente,78,2.0,latin hip hop,2022-05-06,3.0,497509.0,2022-05-26,0.663,...,11.0,-3.510,0.1950,0.229,0.00000,0.219,0.579,196.12,198367.0,Argentina
16385,"Blessd, Justin Quiles, Lenny Tavárez",Medallo,79,3.0,reggaeton,2021-10-27,30.0,493240.0,2022-05-26,0.787,...,4.0,-4.598,0.0768,0.568,0.00051,0.663,0.791,90.02,233453.0,Argentina
16386,"Blessd, Justin Quiles, Lenny Tavárez",Medallo,79,3.0,reggaeton,2021-10-27,30.0,493240.0,2022-05-26,0.787,...,4.0,-4.598,0.0768,0.568,0.00051,0.663,0.791,90.02,233453.0,Argentina
16387,"Blessd, Justin Quiles, Lenny Tavárez",Medallo,79,3.0,reggaeton flow,2021-10-27,30.0,493240.0,2022-05-26,0.787,...,4.0,-4.598,0.0768,0.568,0.00051,0.663,0.791,90.02,233453.0,Argentina
16388,"Eladio Carrion, Nicki Nicole",Nota,82,2.0,trap triste,2022-05-19,1.0,481864.0,2022-05-26,0.700,...,3.0,-5.563,0.3490,0.723,0.00000,0.111,0.643,91.05,159483.0,Argentina

In [96]:
music_removed["release_date"] = pd.to_datetime(music_removed["release_date"])
music_removed["week"] = pd.to_datetime(music_removed["week"])

In [97]:
music_removed.dtypes

artist_names                object
track_name                  object
rank                         int32
artists_num                float64
artist_genre                object
release_date        datetime64[ns]
weeks_on_chart             float64
streams                    float64
week                datetime64[ns]
danceability               float64
energy                     float64
key                        float64
loudness                   float64
speechiness                float64
acousticness               float64
instrumentalness           float64
liveness                   float64
valence                    float64
tempo                      float64
duration                   float64
country                     object
dtype: object

In [98]:
music_removed.count()

artist_names        1130423
track_name          1130423
rank                1130423
artists_num         1130423
artist_genre        1130423
release_date        1130423
weeks_on_chart      1130423
streams             1130423
week                1130423
danceability        1130169
energy              1130169
key                 1130169
loudness            1130169
speechiness         1130169
acousticness        1130169
instrumentalness    1130169
liveness            1130169
valence             1130169
tempo               1130169
duration            1130169
country             1130423
dtype: int64

In [99]:
unique_dates = music_removed['week'].unique()
len(unique_dates)

232

In [100]:
unique_dates = [unique for unique in unique_dates]
len(unique_dates)
unique_dates.sort()
print(unique_dates[0])
print(unique_dates[-1])

2016-12-29T00:00:00.000000000
2022-07-14T00:00:00.000000000

In [101]:
artist_group = music_removed.groupby(music_removed['artist_names'])
artist_grouped = music_removed.groupby(["artist_names", "track_name","country"])["streams"].sum()
artist_grouped_df = pd.DataFrame(artist_grouped).sort_values(['track_name','streams'])
artist_grouped_df.head(60)

                                                                                                                                streams
artist_names                                       track_name                                         country
SyKo                                               #BrooklynBloodPop!                                 Bulgaria                   6046.0
                                                                                                      Ukraine                   43356.0
                                                                                                      Latvia                    50964.0
                                                                                                      Romania                   68026.0
                                                                                                      Lithuania                146408.0
                                                                                                      Estonia                  147633.0
                                                                                                      United Arab Emirates     150579.0
                                                                                                      Saudi Arabia             630012.0
Żabson, Young Igi, Marcin, @atutowy                #FreeBritney                                       Poland                  1243192.0
ElGrandeToto                                       #OuDiriHakka                                       Morocco                 1409291.0
Foyone, Sceno, Kase.O, Dollar Selmouni, Ayax y ... #RapSinCorte L                                     Spain                  49175135.0
Shevy O'shea                                       #RihannaMove                                       Lithuania                 13859.0
YSY A, Bizarrap                                    #Ysya2020 Vol. 6 - Un Flow de Infarto              Argentina                368902.0
Chivv, Eves Laurent                                #readthatagain (feat. Eves Laurent)                Netherlands              398704.0
Jerry Heil, Verka Serduchka                        #МОСКАЛЬ_НЕКРАСІВИЙ                                Ukraine                  190814.0
Jerry Heil                                         #ПОШТА                                             Ukraine                  151326.0
RAVA                                               $P$ - Studio Session #02                           Romania                  343312.0
                                                   $aMAN                                              Romania                  293020.0
Sfera Ebbasta                                      $€ Freestyle                                       Italy                   3534998.0
LIBERATO                                           'NA STORIA 'E 'NA SERA                             Italy                    325936.0
Cody Johnson                                       'Til You Can't                                     Canada                   674455.0
                                                                                                      United States          39930163.0
Eminem, Nate Dogg                                  'Till I Collapse                                   Israel                    53002.0
                                                                                                      Saudi Arabia              56518.0
                                                                                                      Latvia                    69442.0
                                                                                                      Lithuania                 98184.0
                                                                                                      Iceland                  143422.0
                                                                                                      Luxembourg               170734.0
                                                                                                      Estonia                  236266.0
                                                                                                      Ireland                  246834.0
                                                                                                      Slovakia                 393866.0
                                                                                                      Belgium                  416034.0
                                                                                                      Romania                  437024.0
                                                                                                      Bulgaria                 466794.0
                                                                                                      Sweden                   511122.0
                                                                                                      Cyprus                   520672.0
                                                                                                      Czech Republic           647946.0
                                                                                                      Denmark                 1625668.0
                                                                                                      New Zealand             2316820.0
                                                                                                      Norway                  2523078.0
                                                                                                      Hungary                 2602176.0
                                                                                                      Germany                 3040082.0
                                                                                                      Austria                 3547500.0
                                                                                                      Australia               4201006.0
                                                                                                      Finland                 4554580.0
                                                                                                      Switzerland             5210862.0
                                                                                                      United Kingdom          6920778.0
                                                                                                      Canada                 29667006.0
                                                                                                      United States          55968696.0
                                                                                                      Global                132510730.0
SEVENTEEN                                          'bout you                                          Korea                     25767.0
                                                                                                      Philippines              279367.0
Blue Öyster Cult                                   (Don't Fear) The Reaper                            Canada                   212241.0
Kay Starr                                          (Everybody's Waitin' For) The Man With The Bag ... Canada                   602294.0
                                                                                                      United States           3999663.0
DJ Totti, Shehab                                   (Explicit version) منافقين                         Egypt                     57476.0
Egor Kreed                                         (Ne)idealna                                        Estonia                    6882.0
                                                                                                      Latvia                    14661.0
Gibbs                                              (Po)ciąg dalszy nastąpi                            Ukraine                   27925.0
                                                                                                      Poland                  5964736.0

In [102]:
music_removed['country'].unique()

array(['Argentina', 'Australia', 'Austria', 'Belarus', 'Belgium',
       'Bolivia', 'Brazil', 'Bulgaria', 'Canada', 'Chile', 'Colombia',
       'Costa Rica', 'Cyprus', 'Czech Republic', 'Denmark',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Estonia',
       'Finland', 'France', 'Germany', 'Global', 'Greece', 'Guatemala',
       'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan', 'Kazakhstan',
       'Korea', 'Latvia', 'Lithuania', 'Luxembourg', 'Malaysia', 'Mexico',
       'Morocco', 'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria',
       'Norway', 'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Romania', 'Saudi Arabia', 'Singapore',
       'Slovakia', 'South Africa', 'Spain', 'Sweden', 'Switzerland',
       'Taiwan', 'Thailand', 'Turkey', 'United Arab Emirates',
       'United Kingdom', 'Ukraine', 'Uruguay', 'United States',
       'Venezuela', 'Vietnam'], dtype=object)

In [103]:
df_w_countries = music_removed.loc[music_removed['country'] != 'Global']
df_w_countries['country'].unique()
df_w_countries.head()

,artist_names,track_name,rank,artists_num,artist_genre,release_date,weeks_on_chart,streams,week,danceability,...,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,country
16384,"Bad Bunny, Tony Dize",La Corriente,78,2.0,latin hip hop,2022-05-06,3.0,497509.0,2022-05-26,0.663,...,11.0,-3.510,0.1950,0.229,0.00000,0.219,0.579,196.12,198367.0,Argentina
16385,"Blessd, Justin Quiles, Lenny Tavárez",Medallo,79,3.0,reggaeton,2021-10-27,30.0,493240.0,2022-05-26,0.787,...,4.0,-4.598,0.0768,0.568,0.00051,0.663,0.791,90.02,233453.0,Argentina
16386,"Blessd, Justin Quiles, Lenny Tavárez",Medallo,79,3.0,reggaeton,2021-10-27,30.0,493240.0,2022-05-26,0.787,...,4.0,-4.598,0.0768,0.568,0.00051,0.663,0.791,90.02,233453.0,Argentina
16387,"Blessd, Justin Quiles, Lenny Tavárez",Medallo,79,3.0,reggaeton flow,2021-10-27,30.0,493240.0,2022-05-26,0.787,...,4.0,-4.598,0.0768,0.568,0.00051,0.663,0.791,90.02,233453.0,Argentina
16388,"Eladio Carrion, Nicki Nicole",Nota,82,2.0,trap triste,2022-05-19,1.0,481864.0,2022-05-26,0.700,...,3.0,-5.563,0.3490,0.723,0.00000,0.111,0.643,91.05,159483.0,Argentina

In [104]:
countries_grouped =df_w_countries.groupby(["artist_names", "track_name","country"])["streams"].sum()
df_countries_grouped = pd.DataFrame(countries_grouped).sort_values(['track_name','streams'])
df_countries_grouped.head(50)

                                                                                                                  streams
artist_names                                       track_name                            country
SyKo                                               #BrooklynBloodPop!                    Bulgaria                  6046.0
                                                                                         Ukraine                  43356.0
                                                                                         Latvia                   50964.0
                                                                                         Romania                  68026.0
                                                                                         Lithuania               146408.0
                                                                                         Estonia                 147633.0
                                                                                         United Arab Emirates    150579.0
                                                                                         Saudi Arabia            630012.0
Żabson, Young Igi, Marcin, @atutowy                #FreeBritney                          Poland                 1243192.0
ElGrandeToto                                       #OuDiriHakka                          Morocco                1409291.0
Foyone, Sceno, Kase.O, Dollar Selmouni, Ayax y ... #RapSinCorte L                        Spain                 49175135.0
Shevy O'shea                                       #RihannaMove                          Lithuania                13859.0
YSY A, Bizarrap                                    #Ysya2020 Vol. 6 - Un Flow de Infarto Argentina               368902.0
Chivv, Eves Laurent                                #readthatagain (feat. Eves Laurent)   Netherlands             398704.0
Jerry Heil, Verka Serduchka                        #МОСКАЛЬ_НЕКРАСІВИЙ                   Ukraine                 190814.0
Jerry Heil                                         #ПОШТА                                Ukraine                 151326.0
RAVA                                               $P$ - Studio Session #02              Romania                 343312.0
                                                   $aMAN                                 Romania                 293020.0
Sfera Ebbasta                                      $€ Freestyle                          Italy                  3534998.0
LIBERATO                                           'NA STORIA 'E 'NA SERA                Italy                   325936.0
Cody Johnson                                       'Til You Can't                        Canada                  674455.0
                                                                                         United States         39930163.0
Eminem, Nate Dogg                                  'Till I Collapse                      Israel                   53002.0
                                                                                         Saudi Arabia             56518.0
                                                                                         Latvia                   69442.0
                                                                                         Lithuania                98184.0
                                                                                         Iceland                 143422.0
                                                                                         Luxembourg              170734.0
                                                                                         Estonia                 236266.0
                                                                                         Ireland                 246834.0
                                                                                         Slovakia                393866.0
                                                                                         Belgium                 416034.0
                                                                                         Romania                 437024.0
                                                                                         Bulgaria                466794.0
                                                                                         Sweden                  511122.0
                                                                                         Cyprus                  520672.0
                                                                                         Czech Republic          647946.0
                                                                                         Denmark                1625668.0
                                                                                         New Zealand            2316820.0
                                                                                         Norway                 2523078.0
                                                                                         Hungary                2602176.0
                                                                                         Germany                3040082.0
                                                                                         Austria                3547500.0
                                                                                         Australia              4201006.0
                                                                                         Finland                4554580.0
                                                                                         Switzerland            5210862.0
                                                                                         United Kingdom         6920778.0
                                                                                         Canada                29667006.0
                                                                                         United States         55968696.0
SEVENTEEN                                          'bout you                             Korea                    25767.0

In [105]:
usa_df = music_removed.loc[music_removed['country'] == 'United States']
usa_df

,artist_names,track_name,rank,artists_num,artist_genre,release_date,weeks_on_chart,streams,week,danceability,...,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration,country
1736825,Harry Styles,As It Was,1,1.0,pop,2022-03-31,1.0,24686367.0,2022-04-07,0.520,...,6.0,-5.338,0.0557,0.34200,0.001010,0.3110,0.662,173.930,167303.0,United States
1736826,Glass Animals,Heat Waves,2,1.0,shiver pop,2020-08-06,71.0,6228260.0,2022-04-07,0.761,...,11.0,-6.900,0.0944,0.44000,0.000007,0.0921,0.531,80.870,238805.0,United States
1736827,Olivia Rodrigo,good 4 u,5,1.0,pop,2021-05-21,47.0,4361310.0,2022-04-07,0.563,...,9.0,-5.044,0.1540,0.33500,0.000000,0.0849,0.688,166.928,178147.0,United States
1736828,Lil Tjay,In My Head,7,1.0,brooklyn drill,2022-04-01,1.0,4216423.0,2022-04-07,0.684,...,1.0,-6.885,0.1210,0.15900,0.000000,0.1020,0.407,143.049,135264.0,United States
1736829,Kodak Black,Super Gremlin,9,1.0,melodic rap,2022-02-25,19.0,4022821.0,2022-04-07,0.825,...,2.0,-6.634,0.1440,0.00265,0.000000,0.3570,0.106,72.993,200548.0,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1758965,"Waka Flocka Flame, Roscoe Dash, Wale",No Hands (feat. Roscoe Dash & Wale),195,3.0,gangster rap,2010-10-01,1.0,1572153.0,2022-03-03,0.760,...,1.0,-6.366,0.0391,0.00544,0.000000,0.2410,0.361,131.497,263773.0,United States
1758966,"Pooh Shiesty, Lil Durk",Back In Blood (feat. Lil Durk),199,2.0,trap,2021-02-05,41.0,1558973.0,2022-03-03,0.759,...,8.0,-8.256,0.3840,0.15100,0.000000,0.1260,0.831,146.933,184490.0,United States
1758967,"Pooh Shiesty, Lil Durk",Back In Blood (feat. Lil Durk),199,2.0,trap,2021-02-05,41.0,1558973.0,2022-03-03,0.759,...,8.0,-8.256,0.3840,0.15100,0.000000,0.1260,0.831,146.933,184490.0,United States
1758968,"ACRAZE, Cherish",Do It To It,200,2.0,0,2021-08-20,15.0,1555951.0,2022-03-03,0.854,...,11.0,-8.262,0.0886,0.02090,0.054200,0.0703,0.637,124.927,157890.0,United States
1758969,"ACRAZE, Cherish",Do It To It,200,2.0,urban contemporary,2021-08-20,15.0,1555951.0,2022-03-03,0.854,...,11.0,-8.262,0.0886,0.02090,0.054200,0.0703,0.637,124.927,157890.0,United States

In [106]:
dates_unique = usa_df['week'].unique()
len(dates_unique)

76

In [ ]:
df_w_countries = df_w_countries[]